/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edwardstock_leveldb_implementation_NativeIterator */

#ifndef _Included_com_edwardstock_leveldb_implementation_NativeIterator
#define _Included_com_edwardstock_leveldb_implementation_NativeIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edwardstock_leveldb_implementation_NativeIterator
 * Method:    nclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_edwardstock_leveldb_implementation_NativeIterator_00024Companion_nclose
    (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeIterator
 * Method:    nvalid
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_edwardstock_leveldb_implementation_NativeIterator_00024Companion_nvalid
    (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeIterator
 * Method:    nseek
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL
Java_com_edwardstock_leveldb_implementation_NativeIterator_00024Companion_nseek
    (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeIterator
 * Method:    nseekToFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_edwardstock_leveldb_implementation_NativeIterator_00024Companion_nseekToFirst
    (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeIterator
 * Method:    nseekToLast
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_edwardstock_leveldb_implementation_NativeIterator_00024Companion_nseekToLast
    (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeIterator
 * Method:    nnext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_edwardstock_leveldb_implementation_NativeIterator_00024Companion_nnext
    (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeIterator
 * Method:    nprev
 * Signature: (J)V
 */
JNIEXPORT void JNICALL
Java_com_edwardstock_leveldb_implementation_NativeIterator_00024Companion_nprev
    (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeIterator
 * Method:    nkey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_edwardstock_leveldb_implementation_NativeIterator_00024Companion_nkey
    (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeIterator
 * Method:    nvalue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL
Java_com_edwardstock_leveldb_implementation_NativeIterator_00024Companion_nvalue
    (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
