/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edwardstock_leveldb_implementation_NativeWriteBatch */

#ifndef _Included_com_edwardstock_leveldb_implementation_NativeWriteBatch
#define _Included_com_edwardstock_leveldb_implementation_NativeWriteBatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_edwardstock_leveldb_implementation_NativeWriteBatch
 * Method:    ncreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_edwardstock_leveldb_implementation_NativeWriteBatch_00024Companion_ncreate
    (JNIEnv *, jobject);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeWriteBatch
 * Method:    nput
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_implementation_NativeWriteBatch_00024Companion_nput
(JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeWriteBatch
 * Method:    ndelete
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_implementation_NativeWriteBatch_00024Companion_ndelete
(JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_edwardstock_leveldb_implementation_NativeWriteBatch
 * Method:    nclose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_implementation_NativeWriteBatch_00024Companion_nclose
(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif