/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edwardstock_leveldb_LevelDBNativeProvider */

#ifndef _Included_com_edwardstock_leveldb_LevelDBNativeProvider
#define _Included_com_edwardstock_leveldb_LevelDBNativeProvider
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbOpen
 * Signature: (ZZIIILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbOpen
        (JNIEnv *, jobject, jboolean, jboolean, jint, jint, jint, jstring);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbDestroy
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbDestroy
(JNIEnv *, jobject, jstring);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbRepair
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbRepair
(JNIEnv *, jobject, jstring);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    batchCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_batchCreate
        (JNIEnv *, jobject);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    batchClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_batchClose
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    batchDelete
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_batchDelete
(JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    batchPut
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_batchPut
(JNIEnv *, jobject, jlong, jbyteArray, jbyteArray);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    iteratorValue
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_iteratorValue
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    iteratorKey
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_iteratorKey
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    iteratorPrev
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_iteratorPrev
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    iteratorNext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_iteratorNext
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    iteratorSeekToLast
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_iteratorSeekToLast
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    iteratorSeekToFirst
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_iteratorSeekToFirst
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    iteratorSeek
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_iteratorSeek
(JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    iteratorValidate
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_iteratorValidate
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    iteratorClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_iteratorClose
(JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbReleaseSnapshot
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbReleaseSnapshot
(JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbSnapshot
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbSnapshot
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbIterate
 * Signature: (JZLjava/lang/Long;)J
 */
JNIEXPORT jlong JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbIterate
        (JNIEnv *, jobject, jlong, jboolean, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbGetProperty
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbGetProperty
        (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbGet
 * Signature: (J[BLjava/lang/Long;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbGet
        (JNIEnv *, jobject, jlong, jbyteArray, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbWrite
 * Signature: (JZJ)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbWrite
(JNIEnv *, jobject, jlong, jboolean, jlong);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbDelete
 * Signature: (JZ[B)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbDelete
(JNIEnv *, jobject, jlong, jboolean, jbyteArray);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbPut
 * Signature: (JZ[B[B)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbPut
(JNIEnv *, jobject, jlong, jboolean, jbyteArray, jbyteArray);

/*
 * Class:     com_edwardstock_leveldb_LevelDBNativeProvider
 * Method:    dbClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_edwardstock_leveldb_internal_LevelDBNativeProvider_dbClose
(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
